// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <143940725+FaDeOkno@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <logkedr18@gmail.com>
// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 SX-7 <92227810+SX-7@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// SPDX-FileCopyrightText: (existing copyrights)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Common.Progression;
using Content.Goobstation.Common.Research;
using Content.Goobstation.Shared.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    private EntityUid _entity;
    private Type _nodeType = default!;
    private Type _disciplineType = default!;
    private ProtoId<IProgressionNode>? _currentNode;
    public Dictionary<string, ResearchAvailability> List = new();
    public int Points = 0;
    private bool _draggin;
    private Vector2 _position = new(45, 250);
    private float _zoom = 1f;
    private bool _isInitialized;
    private const float MinZoom = 0.5f;
    private const float MaxZoom = 2f;
    private const float ZoomSpeed = 0.125f;

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entityManager.System<ResearchSystem>();
        _sprite = _entityManager.System<SpriteSystem>();
        _accessReader = _entityManager.System<AccessReaderSystem>();
        StaticSprite.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(new("_Goobstation/Interface/rnd-static.rsi"), "static"));
        StaticSprite.DisplayRect.CanShrink = true;
        StaticSprite.DisplayRect.Stretch = TextureRect.StretchMode.Scale;

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();

        UpdatePanels(List);
        Recenter();
    }

    public void Initialize(string nodeTypeId, string disciplineTypeId)
    {
        if (_isInitialized)
            return;

        _nodeType = _prototype.GetKindType(nodeTypeId);
        _disciplineType = _prototype.GetKindType(disciplineTypeId);
        _isInitialized = true;
    }

    public void SetEntity(EntityUid entity)
        => _entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        if (!_isInitialized)
            return;

        DragContainer.RemoveAllChildren();
        List = dict;

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);
            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value);
            DragContainer.AddChild(control);
            LayoutContainer.SetPosition(control, _position + proto.Position * 150 * _zoom);
            control.SelectAction += SelectNode;

            if (tech.Key.Equals(_currentNode?.Id))
                SelectNode(proto, tech.Value);
        }
    }

    // still needs genericization  i think
    public void UpdateInformationPanel(int points)
    {
        if (!_isInitialized)
            return;

        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entityManager.TryGetComponent(_entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index(disciplineId);
            var tier = _research.GetTierCompletionPercentage(database, discipline, _prototype);

            // i'm building the small-ass control here to spare me some mild annoyance in making a new file
            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10,
                    }
                }
            };
            TierDisplayContainer.AddChild(control);
        }
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        _position += args.Relative;

        // Move all tech
        foreach (var child in DragContainer.Children)
        {
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
        }
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        var oldZoom = _zoom;

        if (args.Delta.Y > 0)
            _zoom += ZoomSpeed;
        else
            _zoom -= ZoomSpeed;

        _zoom = Math.Clamp(_zoom, MinZoom, MaxZoom);

        if (MathHelper.CloseTo(oldZoom, _zoom))
            return;

        foreach (var child in DragContainer.Children)
        {
            if (child is not FancyResearchConsoleItem research)
                continue;

            var pos = research.Prototype.Position * 150;
            LayoutContainer.SetPosition(child, _position + pos * _zoom);
            research.SetScale(_zoom);
        }
        args.Handle();
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion

    /// <summary>
    /// Selects a progression node and opens the detailed info panel for it.
    /// This method now acts as the "Controller" that prepares generic data for the "View" (the Info Panel).
    /// </summary>
    private void SelectNode(IProgressionNode proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        _currentNode = new ProtoId<IProgressionNode>(proto.ID);
        var unlocks = new List<ProgressionUnlock>();
        var prerequisites = new List<ProgressionUnlock>();
        if (proto is TechnologyPrototype techProto)
        {
            ShowResearchPanel(proto, techProto, ref unlocks, ref prerequisites);
        }

        var control = new FancyTechnologyInfoPanel(
            proto,
            _accessReader.IsAllowed(_player.LocalEntity.Value, _entity),
            availability,
            unlocks,
            prerequisites,
            _prototype,
            _sprite,
            _disciplineType);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    private void ShowResearchPanel(IProgressionNode proto, TechnologyPrototype techProto, ref List<ProgressionUnlock> unlocks, ref List<ProgressionUnlock> prereqs)
    {
        _nodeType = typeof(TechnologyPrototype);
        _disciplineType = typeof(TechDisciplinePrototype);
        prereqs = proto.Prerequisites
            .Select(prereqId => _prototype.Index<TechnologyPrototype>(prereqId))
            .Select(prereqProto => new ProgressionUnlock(
                Loc.GetString(prereqProto.Name),
                Loc.GetString(prereqProto.Description),
                prereqProto.Icon))
            .ToList();
        var latheSystem = _entityManager.System<LatheSystem>();
        foreach (var recipeId in techProto.RecipeUnlocks)
        {
            if (!_prototype.TryIndex(recipeId, out var recipeProto) ||
                recipeProto.Result is not { } resultId ||
                !_prototype.TryIndex<EntityPrototype>(resultId, out var resultProto))
                continue;
            unlocks.Add(new ProgressionUnlock(
                latheSystem.GetRecipeName(recipeProto),
                latheSystem.GetRecipeDescription(recipeProto),
                new SpriteSpecifier.EntityPrototype(resultProto.ID)
            ));
        }
    }

    /// <summary>
    /// Sets <see cref="_position"/> to its default value
    /// </summary>
    private void Recenter()
    {
        _position = new(45, 250);
        foreach (var item in DragContainer.Children)
        {
            if (item is not FancyResearchConsoleItem research)
                continue;

            LayoutContainer.SetPosition(item, _position + research.Prototype.Position * 150 * _zoom);
        }
    }

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }
}
