// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <143940725+FaDeOkno@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <logkedr18@gmail.com>
// SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Common.Research;
using Content.Goobstation.Common.Progression;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    private readonly IPrototypeManager _proto;
    private readonly IProgressionNode _node;
    public Action<IProgressionNode>? BuyAction;


    public FancyTechnologyInfoPanel(IProgressionNode proto, bool hasAccess, ResearchAvailability availability, List<ProgressionUnlock> unlocks, List<ProgressionUnlock> prereqs, IPrototypeManager protoMan, SpriteSystem sprite, Type type)
    {
        RobustXamlLoader.Load(this);
        _proto = protoMan;
        _node = proto;
        if (protoMan.Index(type, proto.Discipline.Id) is not TechDisciplinePrototype discipline)
            return;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(discipline.Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);

        InitializePrerequisites(prereqs, discipline.Color, sprite);
        InitializeUnlocks(unlocks, discipline.Color, sprite);

        ResearchButton.ToolTip = !hasAccess
            ? Loc.GetString("research-console-no-access-popup")
            : null;

        ResearchButton.Text = availability == ResearchAvailability.Researched
            ? Loc.GetString("research-console-menu-server-researched-button")
            : ResearchButton.Text;

        Color? color = availability switch
        {
            ResearchAvailability.Researched => Color.LimeGreen,
            ResearchAvailability.PrereqsMet => Color.Crimson,
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => null
        };
        TechnologyCostLabel.SetMessage(
            Loc.GetString("research-console-tech-cost-label", ("cost", proto.Cost)),
            defaultColor: color
        );

        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;
        ResearchButton.OnPressed += Bought;
    }

    private void InitializePrerequisites(List<ProgressionUnlock> prerequisites, Color color, SpriteSystem sprite)
    {
        NoPrereqLabel.Visible = prerequisites.Count == 0;
        PrereqsContainer.Visible = !NoPrereqLabel.Visible;

        RequiredTechContainer.RemoveAllChildren();
        foreach (var prereq in prerequisites)
        {
            RequiredTechContainer.AddChild(new MiniProgressionCardControl(prereq, color, sprite));
        }
    }

    private void InitializeUnlocks(List<ProgressionUnlock> unlocks, Color color, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var unlock in unlocks)
        {
            UnlocksContainer.AddChild(new MiniProgressionCardControl(unlock, color, sprite));
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        ResearchButton.OnPressed -= Bought;
    }
    private void Bought(BaseButton.ButtonEventArgs args)
    {
        BuyAction?.Invoke(_node);
    }

}
