// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <143940725+FaDeOkno@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <logkedr18@gmail.com>
// SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Common.Progression;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class MiniProgressionCardControl : Control
{
    public MiniProgressionCardControl(ProgressionUnlock unlock, Color disciplineColor, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        Background.ModulateSelfOverride = disciplineColor;
        NameLabel.SetMessage(FormattedMessage.FromUnformatted(unlock.Name));
        Showcase.Texture = sprite.Frame0(unlock.Icon);

        if (unlock.Description == null)
            return;
        var tooltip = new Tooltip();
        tooltip.SetMessage(FormattedMessage.FromUnformatted(unlock.Description));
        Main.TooltipSupplier = _ => tooltip;
    }
}
