name: Tag PR on First Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  tag_on_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals
        id: approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const approvals = reviews.filter(review => review.state === "APPROVED").length;

            if (approvals === 1) {
              console.log("First approval detected!");
              core.setOutput("approved", "true");
            }

      - name: Add label
        if: steps.approvals.outputs.approved == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ["First Approval"]
            });
